# Generated by Django 6.0.3 on 2026-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('prep_time', models.PositiveIntegerField(help_text='Tempo di preparazione in minuti')),
                ('cook_time', models.PositiveIntegerField(blank=True, help_text='Tempo di cottura in minuti', null=True)),
                ('servings', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Media'), ('hard', 'Difficile'), ('longterm', 'Lunga preparazione')], default='easy', max_length=20)),
                ('category', models.CharField(choices=[('appetizer', 'Antipasto'), ('first_course', 'Primo'), ('second_course', 'Secondo'), ('side_dish', 'Contorno'), ('dessert', 'Dolce'), ('other', 'Altro')], default='other', max_length=30)),
                ('cuisine_type', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ricetta',
                'verbose_name_plural': 'Ricette',
                'ordering': ['-created_at'],
            },
        ),
    ]
