# Generated by Django 6.0.3 on 2026-03-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Facile'), ('medium', 'Media'), ('hard', 'Difficile'), ('expert', 'Esperta')], default='easy', max_length=20),
        ),
    ]
